apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-config-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: configDemo
  template:
    metadata:
      labels:
        component: configDemo
    spec:
      containers:
        - name: client
          image: tp6g4cjo4/k8s-config-demo
          ports:
            - containerPort: 8080
#          env:
#            - name: APPLICATION_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: demo-configmap
#                  key: APPLICATION_NAME
#            - name: DATASOURCE_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: demo-secret
#                  key: DATASOURCE_USERNAME
#            - name: DATASOURCE_PWD
#              valueFrom:
#                secretKeyRef:
#                  name: demo-secret
#                  key: DATASOURCE_PWD